[package]
name = "everything-plugin"
version = "0.1.1"
edition = "2024"
description = "Rust binding for Everything's plugin SDK"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["tracing", "winio", "winio-darkmode"]
tracing = ["dep:tracing", "dep:tracing-subscriber", "dep:anstream"]
ui = ["dep:windows-sys", "windows-sys/Win32_UI_WindowsAndMessaging", "dep:futures-channel", "dep:futures-util"]
winio = ["ui", "dep:winio"]
winio-darkmode = ["winio/windows-dark-mode"]

[dependencies]
anstream = { version = "0.6", optional = true }
bon = "3"
futures-channel = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", optional = true }
windows-sys = { version = "0.59", optional = true }

[dependencies.winio]
version = "0.5.0"
default-features = false
optional = true
git = "https://github.com/compio-rs/winio"
rev = "d57fa507ba27a4dc71887f202ec4eb594f5acb0e"

[dev-dependencies]

[[example]]
name = "test"
crate-type = ["cdylib"]
