[package]
name = "everything-plugin"
version = "0.1.1"
edition = "2024"
description = "Rust binding for Everything's plugin SDK"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["tracing"]
tracing = ["dep:tracing", "dep:tracing-subscriber", "dep:anstream"]

[dependencies]
anstream = { version = "0.6", optional = true }
bon = "3"
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", optional = true }

[dev-dependencies]

[[example]]
name = "test"
crate-type = ["cdylib"]
